[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-comprehensions
    "C4",
    # isort
    "I",
]

isort = { known-first-party = ['brazilfiscalreport', 'test'] }

[tool.doc8]
max-line-length = 88
